apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-user
      tier: deployment-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
        tier: deployment-api-user
    spec:
      containers:
        - image: stevejks/udagram-api-user:v1
          name: udagram-api-user
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: project-3-global-config
            - secretRef:
                name: project-3-postgres
            - secretRef:
                name: project-3-aws
