apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
      tier: deployment-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
        tier: deployment-reverseproxy
    spec:
      containers:
        - image: stevejks/udagram-reverseproxy:v1
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
