apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
      tier: deployment-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
        tier: deployment-frontend
    spec:
      containers:
        - image: stevejks/udagram-frontend:v1
          name: udagram-frontend
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 80
