apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-service
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: udagram-frontend
